HEADER:
  label: "Portfolio"
PROJECTS:
  - title: "Budget Monitoring with AWS Budgets and SNS"
    category: "AWS"
    image: "config/assets/projects/aws-budgets.png"
    url: "https://github.com/Ismaeldugg25/budget-monitoring-aws"
  - title: "Centralized Alert Management System with User Notifications and CloudWatch"
    category: "AWS"
    image: "config/assets/projects/0308b86c1986f514cc7ac98748f9c85c_kix.g4x8cy4yvhun.webp"
    url: "https://github.com/Ismaeldugg25/centralized-alert-management-system-aws"
  - title: "AWS Resources Monitoring with CloudWatch Alarms"
    category: "AWS"
    image: "config/assets/projects/Nexus-feat-img2.png"
    url: "https://github.com/Ismaeldugg25/basic-monitoring-cloudwatch-alarms/tree/main"
  - title: "Service Health Notifications System with AWS Health and SNS"
    category: "AWS"
    image: "config/assets/projects/aws health .png"
    url: "https://github.com/Ismaeldugg25/service-health-notifications-aws"
  - title: "EC2 Launch Templates with Auto Scaling"
    category: "AWS"
    image: "config/assets/projects/ec2 asg.png"
    url: "https://github.com/Ismaeldugg25/ec2-launch-templates-auto-scaling"
  - title: "Weather Alert Notifications System with Lambda and SNS"
    category: "AWS"
    image: "config/assets/projects/maxresdefault.jpg"
    url: "https://github.com/Ismaeldugg25/weather-alert-notifications-lambda-sns"
  - title: "API Logging with CloudTrail and S3"
    category: "AWS"
    image: "config/assets/projects/CloudTrail-feat-img-2.png"
    url: "https://github.com/Ismaeldugg25/aws-cloudtrail-api-logging/tree/main"



  


