HEADER:
  label: "Portfolio"
PROJECTS:
  - title: "Budget Monitoring with AWS Budgets and SNS"
    category: "AWS"
    image: "config/assets/projects/aws-budgets.png"
    url: "https://github.com/Ismaeldugg25/budget-monitoring-aws"
  - title: "Centralized Alert Management System with User Notifications and CloudWatch"
    category: "AWS"
    image: "config/assets/projects/0308b86c1986f514cc7ac98748f9c85c_kix.g4x8cy4yvhun.webp"
    url: "https://github.com/Ismaeldugg25/centralized-alert-management-system-aws"
  - title: "AWS Resources Monitoring with CloudWatch Alarms"
    category: "AWS"
    image: "config/assets/projects/Nexus-feat-img2.png"
    url: "https://github.com/Ismaeldugg25/basic-monitoring-cloudwatch-alarms/tree/main"



    
